version: '3'

services:
  frontend:
    image: frontend
    ports:
      - "3000:3000"

  backend:
    image: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/panipro

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

